//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumiendoWebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleados", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Empleados : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APELLIDOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string APELLIDOS {
            get {
                return this.APELLIDOSField;
            }
            set {
                if ((object.ReferenceEquals(this.APELLIDOSField, value) != true)) {
                    this.APELLIDOSField = value;
                    this.RaisePropertyChanged("APELLIDOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.HelloWorldResponse HelloWorld(ConsumiendoWebService.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync(ConsumiendoWebService.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.SaludarResponse Saludar(ConsumiendoWebService.ServiceReference1.SaludarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Saludar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.SaludarResponse> SaludarAsync(ConsumiendoWebService.ServiceReference1.SaludarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardaLog", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.GuardaLogResponse GuardaLog(ConsumiendoWebService.ServiceReference1.GuardaLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardaLog", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardaLogResponse> GuardaLogAsync(ConsumiendoWebService.ServiceReference1.GuardaLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        decimal Sumar(int n1, int n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sumar", ReplyAction="*")]
        System.Threading.Tasks.Task<decimal> SumarAsync(int n1, int n2);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerMesesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMeses", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse ObtenerMeses(ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMeses", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse> ObtenerMesesAsync(ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arreglo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarArreglo", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.GuardarArregloResponse GuardarArreglo(ConsumiendoWebService.ServiceReference1.GuardarArregloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarArreglo", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarArregloResponse> GuardarArregloAsync(ConsumiendoWebService.ServiceReference1.GuardarArregloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerEmpleadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEmpleado", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse ObtenerEmpleado(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse> ObtenerEmpleadoAsync(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarXML", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.EnviarXMLResponse EnviarXML(ConsumiendoWebService.ServiceReference1.EnviarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.EnviarXMLResponse> EnviarXMLAsync(ConsumiendoWebService.ServiceReference1.EnviarXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RetornarJSONResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarJSON", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.RetornarJSONResponse RetornarJSON(ConsumiendoWebService.ServiceReference1.RetornarJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornarJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.RetornarJSONResponse> RetornarJSONAsync(ConsumiendoWebService.ServiceReference1.RetornarJSONRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento json del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarJSON", ReplyAction="*")]
        ConsumiendoWebService.ServiceReference1.GuardarJSONResponse GuardarJSON(ConsumiendoWebService.ServiceReference1.GuardarJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GuardarJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarJSONResponse> GuardarJSONAsync(ConsumiendoWebService.ServiceReference1.GuardarJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumiendoWebService.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumiendoWebService.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Saludar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.SaludarRequestBody Body;
        
        public SaludarRequest() {
        }
        
        public SaludarRequest(ConsumiendoWebService.ServiceReference1.SaludarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public SaludarRequestBody() {
        }
        
        public SaludarRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaludarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaludarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.SaludarResponseBody Body;
        
        public SaludarResponse() {
        }
        
        public SaludarResponse(ConsumiendoWebService.ServiceReference1.SaludarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaludarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaludarResult;
        
        public SaludarResponseBody() {
        }
        
        public SaludarResponseBody(string SaludarResult) {
            this.SaludarResult = SaludarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardaLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardaLog", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardaLogRequestBody Body;
        
        public GuardaLogRequest() {
        }
        
        public GuardaLogRequest(ConsumiendoWebService.ServiceReference1.GuardaLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardaLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public GuardaLogRequestBody() {
        }
        
        public GuardaLogRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardaLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardaLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardaLogResponseBody Body;
        
        public GuardaLogResponse() {
        }
        
        public GuardaLogResponse(ConsumiendoWebService.ServiceReference1.GuardaLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardaLogResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardaLogResult;
        
        public GuardaLogResponseBody() {
        }
        
        public GuardaLogResponseBody(string GuardaLogResult) {
            this.GuardaLogResult = GuardaLogResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMesesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMeses", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.ObtenerMesesRequestBody Body;
        
        public ObtenerMesesRequest() {
        }
        
        public ObtenerMesesRequest(ConsumiendoWebService.ServiceReference1.ObtenerMesesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerMesesRequestBody {
        
        public ObtenerMesesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMesesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMesesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.ObtenerMesesResponseBody Body;
        
        public ObtenerMesesResponse() {
        }
        
        public ObtenerMesesResponse(ConsumiendoWebService.ServiceReference1.ObtenerMesesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerMesesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumiendoWebService.ServiceReference1.ArrayOfString ObtenerMesesResult;
        
        public ObtenerMesesResponseBody() {
        }
        
        public ObtenerMesesResponseBody(ConsumiendoWebService.ServiceReference1.ArrayOfString ObtenerMesesResult) {
            this.ObtenerMesesResult = ObtenerMesesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarArregloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarArreglo", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardarArregloRequestBody Body;
        
        public GuardarArregloRequest() {
        }
        
        public GuardarArregloRequest(ConsumiendoWebService.ServiceReference1.GuardarArregloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarArregloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumiendoWebService.ServiceReference1.ArrayOfString arreglo;
        
        public GuardarArregloRequestBody() {
        }
        
        public GuardarArregloRequestBody(ConsumiendoWebService.ServiceReference1.ArrayOfString arreglo) {
            this.arreglo = arreglo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarArregloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarArregloResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardarArregloResponseBody Body;
        
        public GuardarArregloResponse() {
        }
        
        public GuardarArregloResponse(ConsumiendoWebService.ServiceReference1.GuardarArregloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarArregloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarArregloResult;
        
        public GuardarArregloResponseBody() {
        }
        
        public GuardarArregloResponseBody(string GuardarArregloResult) {
            this.GuardarArregloResult = GuardarArregloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequestBody Body;
        
        public ObtenerEmpleadoRequest() {
        }
        
        public ObtenerEmpleadoRequest(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerEmpleadoRequestBody {
        
        public ObtenerEmpleadoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponseBody Body;
        
        public ObtenerEmpleadoResponse() {
        }
        
        public ObtenerEmpleadoResponse(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEmpleadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumiendoWebService.ServiceReference1.Empleados[] ObtenerEmpleadoResult;
        
        public ObtenerEmpleadoResponseBody() {
        }
        
        public ObtenerEmpleadoResponseBody(ConsumiendoWebService.ServiceReference1.Empleados[] ObtenerEmpleadoResult) {
            this.ObtenerEmpleadoResult = ObtenerEmpleadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarXML", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.EnviarXMLRequestBody Body;
        
        public EnviarXMLRequest() {
        }
        
        public EnviarXMLRequest(ConsumiendoWebService.ServiceReference1.EnviarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public EnviarXMLRequestBody() {
        }
        
        public EnviarXMLRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.EnviarXMLResponseBody Body;
        
        public EnviarXMLResponse() {
        }
        
        public EnviarXMLResponse(ConsumiendoWebService.ServiceReference1.EnviarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviarXMLResult;
        
        public EnviarXMLResponseBody() {
        }
        
        public EnviarXMLResponseBody(string EnviarXMLResult) {
            this.EnviarXMLResult = EnviarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornarJSON", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.RetornarJSONRequestBody Body;
        
        public RetornarJSONRequest() {
        }
        
        public RetornarJSONRequest(ConsumiendoWebService.ServiceReference1.RetornarJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetornarJSONRequestBody {
        
        public RetornarJSONRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetornarJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetornarJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.RetornarJSONResponseBody Body;
        
        public RetornarJSONResponse() {
        }
        
        public RetornarJSONResponse(ConsumiendoWebService.ServiceReference1.RetornarJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornarJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornarJSONResult;
        
        public RetornarJSONResponseBody() {
        }
        
        public RetornarJSONResponseBody(string RetornarJSONResult) {
            this.RetornarJSONResult = RetornarJSONResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarJSON", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardarJSONRequestBody Body;
        
        public GuardarJSONRequest() {
        }
        
        public GuardarJSONRequest(ConsumiendoWebService.ServiceReference1.GuardarJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string json;
        
        public GuardarJSONRequestBody() {
        }
        
        public GuardarJSONRequestBody(string json) {
            this.json = json;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GuardarJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GuardarJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumiendoWebService.ServiceReference1.GuardarJSONResponseBody Body;
        
        public GuardarJSONResponse() {
        }
        
        public GuardarJSONResponse(ConsumiendoWebService.ServiceReference1.GuardarJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GuardarJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GuardarJSONResult;
        
        public GuardarJSONResponseBody() {
        }
        
        public GuardarJSONResponseBody(string GuardarJSONResult) {
            this.GuardarJSONResult = GuardarJSONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : ConsumiendoWebService.ServiceReference1.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<ConsumiendoWebService.ServiceReference1.ServiciosSoap>, ConsumiendoWebService.ServiceReference1.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.HelloWorldResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.HelloWorld(ConsumiendoWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumiendoWebService.ServiceReference1.HelloWorldRequest inValue = new ConsumiendoWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.HelloWorldRequestBody();
            ConsumiendoWebService.ServiceReference1.HelloWorldResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.HelloWorldResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.HelloWorldAsync(ConsumiendoWebService.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            ConsumiendoWebService.ServiceReference1.HelloWorldRequest inValue = new ConsumiendoWebService.ServiceReference1.HelloWorldRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.HelloWorldRequestBody();
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.SaludarResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.Saludar(ConsumiendoWebService.ServiceReference1.SaludarRequest request) {
            return base.Channel.Saludar(request);
        }
        
        public string Saludar(string nombre) {
            ConsumiendoWebService.ServiceReference1.SaludarRequest inValue = new ConsumiendoWebService.ServiceReference1.SaludarRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            ConsumiendoWebService.ServiceReference1.SaludarResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).Saludar(inValue);
            return retVal.Body.SaludarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.SaludarResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.SaludarAsync(ConsumiendoWebService.ServiceReference1.SaludarRequest request) {
            return base.Channel.SaludarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.SaludarResponse> SaludarAsync(string nombre) {
            ConsumiendoWebService.ServiceReference1.SaludarRequest inValue = new ConsumiendoWebService.ServiceReference1.SaludarRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.SaludarRequestBody();
            inValue.Body.nombre = nombre;
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).SaludarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.GuardaLogResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardaLog(ConsumiendoWebService.ServiceReference1.GuardaLogRequest request) {
            return base.Channel.GuardaLog(request);
        }
        
        public string GuardaLog(string mensaje) {
            ConsumiendoWebService.ServiceReference1.GuardaLogRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardaLogRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardaLogRequestBody();
            inValue.Body.mensaje = mensaje;
            ConsumiendoWebService.ServiceReference1.GuardaLogResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardaLog(inValue);
            return retVal.Body.GuardaLogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardaLogResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardaLogAsync(ConsumiendoWebService.ServiceReference1.GuardaLogRequest request) {
            return base.Channel.GuardaLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardaLogResponse> GuardaLogAsync(string mensaje) {
            ConsumiendoWebService.ServiceReference1.GuardaLogRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardaLogRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardaLogRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardaLogAsync(inValue);
        }
        
        public decimal Sumar(int n1, int n2) {
            return base.Channel.Sumar(n1, n2);
        }
        
        public System.Threading.Tasks.Task<decimal> SumarAsync(int n1, int n2) {
            return base.Channel.SumarAsync(n1, n2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.ObtenerMeses(ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest request) {
            return base.Channel.ObtenerMeses(request);
        }
        
        public ConsumiendoWebService.ServiceReference1.ArrayOfString ObtenerMeses() {
            ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest inValue = new ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.ObtenerMesesRequestBody();
            ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).ObtenerMeses(inValue);
            return retVal.Body.ObtenerMesesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.ObtenerMesesAsync(ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest request) {
            return base.Channel.ObtenerMesesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerMesesResponse> ObtenerMesesAsync() {
            ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest inValue = new ConsumiendoWebService.ServiceReference1.ObtenerMesesRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.ObtenerMesesRequestBody();
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).ObtenerMesesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.GuardarArregloResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardarArreglo(ConsumiendoWebService.ServiceReference1.GuardarArregloRequest request) {
            return base.Channel.GuardarArreglo(request);
        }
        
        public string GuardarArreglo(ConsumiendoWebService.ServiceReference1.ArrayOfString arreglo) {
            ConsumiendoWebService.ServiceReference1.GuardarArregloRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardarArregloRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardarArregloRequestBody();
            inValue.Body.arreglo = arreglo;
            ConsumiendoWebService.ServiceReference1.GuardarArregloResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardarArreglo(inValue);
            return retVal.Body.GuardarArregloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarArregloResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardarArregloAsync(ConsumiendoWebService.ServiceReference1.GuardarArregloRequest request) {
            return base.Channel.GuardarArregloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarArregloResponse> GuardarArregloAsync(ConsumiendoWebService.ServiceReference1.ArrayOfString arreglo) {
            ConsumiendoWebService.ServiceReference1.GuardarArregloRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardarArregloRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardarArregloRequestBody();
            inValue.Body.arreglo = arreglo;
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardarArregloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.ObtenerEmpleado(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest request) {
            return base.Channel.ObtenerEmpleado(request);
        }
        
        public ConsumiendoWebService.ServiceReference1.Empleados[] ObtenerEmpleado() {
            ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest inValue = new ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequestBody();
            ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).ObtenerEmpleado(inValue);
            return retVal.Body.ObtenerEmpleadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.ObtenerEmpleadoAsync(ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest request) {
            return base.Channel.ObtenerEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoResponse> ObtenerEmpleadoAsync() {
            ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest inValue = new ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.ObtenerEmpleadoRequestBody();
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).ObtenerEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.EnviarXMLResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.EnviarXML(ConsumiendoWebService.ServiceReference1.EnviarXMLRequest request) {
            return base.Channel.EnviarXML(request);
        }
        
        public string EnviarXML(string xml) {
            ConsumiendoWebService.ServiceReference1.EnviarXMLRequest inValue = new ConsumiendoWebService.ServiceReference1.EnviarXMLRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.EnviarXMLRequestBody();
            inValue.Body.xml = xml;
            ConsumiendoWebService.ServiceReference1.EnviarXMLResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).EnviarXML(inValue);
            return retVal.Body.EnviarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.EnviarXMLResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.EnviarXMLAsync(ConsumiendoWebService.ServiceReference1.EnviarXMLRequest request) {
            return base.Channel.EnviarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.EnviarXMLResponse> EnviarXMLAsync(string xml) {
            ConsumiendoWebService.ServiceReference1.EnviarXMLRequest inValue = new ConsumiendoWebService.ServiceReference1.EnviarXMLRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.EnviarXMLRequestBody();
            inValue.Body.xml = xml;
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).EnviarXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.RetornarJSONResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.RetornarJSON(ConsumiendoWebService.ServiceReference1.RetornarJSONRequest request) {
            return base.Channel.RetornarJSON(request);
        }
        
        public string RetornarJSON() {
            ConsumiendoWebService.ServiceReference1.RetornarJSONRequest inValue = new ConsumiendoWebService.ServiceReference1.RetornarJSONRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.RetornarJSONRequestBody();
            ConsumiendoWebService.ServiceReference1.RetornarJSONResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).RetornarJSON(inValue);
            return retVal.Body.RetornarJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.RetornarJSONResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.RetornarJSONAsync(ConsumiendoWebService.ServiceReference1.RetornarJSONRequest request) {
            return base.Channel.RetornarJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.RetornarJSONResponse> RetornarJSONAsync() {
            ConsumiendoWebService.ServiceReference1.RetornarJSONRequest inValue = new ConsumiendoWebService.ServiceReference1.RetornarJSONRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.RetornarJSONRequestBody();
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).RetornarJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumiendoWebService.ServiceReference1.GuardarJSONResponse ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardarJSON(ConsumiendoWebService.ServiceReference1.GuardarJSONRequest request) {
            return base.Channel.GuardarJSON(request);
        }
        
        public string GuardarJSON(string json) {
            ConsumiendoWebService.ServiceReference1.GuardarJSONRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardarJSONRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardarJSONRequestBody();
            inValue.Body.json = json;
            ConsumiendoWebService.ServiceReference1.GuardarJSONResponse retVal = ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardarJSON(inValue);
            return retVal.Body.GuardarJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarJSONResponse> ConsumiendoWebService.ServiceReference1.ServiciosSoap.GuardarJSONAsync(ConsumiendoWebService.ServiceReference1.GuardarJSONRequest request) {
            return base.Channel.GuardarJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumiendoWebService.ServiceReference1.GuardarJSONResponse> GuardarJSONAsync(string json) {
            ConsumiendoWebService.ServiceReference1.GuardarJSONRequest inValue = new ConsumiendoWebService.ServiceReference1.GuardarJSONRequest();
            inValue.Body = new ConsumiendoWebService.ServiceReference1.GuardarJSONRequestBody();
            inValue.Body.json = json;
            return ((ConsumiendoWebService.ServiceReference1.ServiciosSoap)(this)).GuardarJSONAsync(inValue);
        }
    }
}
